api_version = "2025-04"

[[extensions]]
type = "theme"
name = "AI Skin Analysis"
handle = "skin-analysis"

[extensions.capabilities]
block_progress = false

[[extensions.targeting]]
module = "./blocks/skin-analysis.liquid"
target = "section"
